### ISSUE TITLE
Adding a webhook

### ISSUE THREAD

**Issue by retorquere** [karlpokus/trobot#1]
When I add a webhook through the cli, it asks me for a "Model id". What is this model, and how do I find its ID?

**Comment by karlpokus** [comment]
Hi @retorquere ! A model is a board, card or a list. You can find its id by adding `.json` to the end of a board url and then dig through all the raw data from that board. See [readme](https://github.com/karlpokus/trobot/blob/master/README.md) for details.

**Comment by retorquere** [comment]
So just like the userid then. Alright, thanks. Isn't there a way to automate finding these? Like listing the boards and getting their modelIds that way?

**Comment by karlpokus** [comment]
> a way to automate finding these?

Not that I'm aware of. Maybe board_Id is part of a url somewhere but lists and cards I think you must dig through the raw json. If you find a simpler solution please let me know :)

**Comment by retorquere** [comment]
There must be a way. Butler for Trello can do it. I'll let you know if I find out how.

**Comment by karlpokus** [comment]
Have a look at the Trello api docs. There’s probably some method to query the data you look for. Rumaging through raw json is tedious I know.

**Comment by karlpokus** [comment]
@retorquere Try these

https://developers.trello.com/v1.0/reference#boardsboardidtest
https://developers.trello.com/v1.0/reference#boardsboardidlists

**Comment by karlpokus** [comment]
@retorquere did it work? Can I close this issue?

**Comment by retorquere** [comment]
Yes, sorry.

**Comment by karlpokus** [comment]
no probs
